image: "debian:stretch"

build:
  stage: build
  before_script:
    - apt-get update -y
    - apt-get install -y make python3-pip
    - pip3 install -r requirements.txt
  script:
    - make otf ttf webfonts
  artifacts:
    paths:
    - build/

test:
  stage: test
  before_script:
    - apt-get update -y
    - apt-get install -y make libharfbuzz-bin python3-pip fntsample
    - pip3 install -r requirements.txt
  script:
    - make test

pages:
  stage: deploy
  before_script:
    - apt-get update -y
    - apt-get install -y make python3-pip
    - pip3 install -r requirements.txt
  script:
    - make webfonts
    - mkdir .public
    - cp -r build tests .public
    - mv .public public
  artifacts:
    paths:
    - public
  only:
    - master
